### ISSUE TITLE
.16 Fix - Mod Command

### ISSUE THREAD

**Issue by TWLTriston** [Valansch/RedMew#130] opened 2017-12-14 16:54 UTC
When the server issues the MOD command, server responds with achievements will be disabled
![Image](https://media.discordapp.net/attachments/344857366900244490/390894229859336195/unknown.png?width=1182&height=326)
https://media.discordapp.net/attachments/344857366900244490/390894229859336195/unknown.png?width=1182&height=326

**Comment by Valansch** [comment] 2017-12-15 14:55
Too bad, do you know if any way to disable achievments outright? My first solution would be to just run `/c` twice before the regulars

**Comment by TWLTriston** [comment] 2017-12-15 15:04
Agreed, run it twice.

**Comment by Valansch** [comment] 2017-12-16 13:25
I just tried launching a new scenario from the server and could not reproduce this. Maybe 0.16.4 fixed it?

**Comment by Valansch** [comment] 2017-12-25 21:19
fixed on backend

**Closed by Valansch** 2017-12-25 21:19 UTC
